### ISSUE TITLE
bundle size

### ISSUE THREAD

**Issue by mfulton26** [twilio/twilio-taskrouter.js#128]
My team is trying to reduce the size of our app and `twilio-taskrouter` is one of the larger dependencies in the web app. Can efforts be made to reduce the size?

Two opportunities I see are:
1. Use built-in web `fetch` API instead of `axios` (either directly or via a thin wrapper for convenience methods, e.g. [`ky`](https://github.com/sindresorhus/ky)).
2. Avoid loading all (or any) of Lodash. Importing functions directly (rather than through `_`) should allow tree shaking for webpack/rollup/etc. Another option is to use [Lodash custom builds](https://lodash.com/custom-builds). Some or all of the usages can be replaced using modern ES built-ins too. `twilio-taskrouter` currently only uses 13 methods from `lodash` (excluding a few other usages in tests/specs):
    1. difference
    1. every
    1. filter
    1. inRange
    1. isBoolean
    1. isDate
    1. isEmpty
    1. isInteger
    1. isNil
    1. isObject
    1. isString
    1. pick
    1. upperFirst

**Comment by AndreyTwilio** [comment]
Thanks @mfulton26, we will go ahead and integrate proposed change for lodash. However axios dependency is slightly more complex, since we need to make sure this package can work on Mobile using React Native.

**Comment by mfulton26** [comment]
> Thanks @mfulton26, we will go ahead and integrate proposed change for lodash. However axios dependency is slightly more complex, since we need to make sure this package can work on Mobile using React Native.

Sounds good to me. I think pulling in all of `lodash` into bundled web apps was my main concern. It does, however, appear that React Native does support the Fetch API: https://reactnative.dev/docs/network. Long term it may be good to move off of `axios`. (One less dependency to keep up to date, patch for new security vulnerability alerts, etc.)

Thank you.
