### ISSUE TITLE
worker.update not avaliable

### ISSUE THREAD

**Issue by aveeday** [twilio/twilio-taskrouter.js#19]
https://www.twilio.com/docs/taskrouter/js-sdk/workspace/worker#update

this method does not exist in source and produce error

https://github.com/twilio/twilio-taskrouter.js/blob/0.5.1/lib/Worker.js

**Comment by AndreyTwilio** [comment]
@aveeday documentation that you are pointing to is relevant to TR SDK v1. This repo is for second version of Task Router SDK. Please use [this documentation](https://twilio.github.io/twilio-taskrouter.js/index.html).
