### ISSUE TITLE
Occasional uncaught exception

### ISSUE THREAD

**Issue by cfluke-twilio** [twilio/twilio-taskrouter.js#38]
On rare occasion, I am getting a network timeout uncaught exception being thrown from axios. 

`"level":"error","message":"uncaughtException: timeout of 5000ms exceeded\nError: timeout of 5000ms exceeded\n    at e.exports (/mytestproject/node_modules/twilio-taskrouter/dist/index.commonjs2.js:10:83369)\n    at Timeout._onTimeout (/mytestproject/node_modules/twilio-taskrouter/dist/index.commonjs2.js:10:186399)\n    at listOnTimeout (node:internal/timers:556:17)\n    at processTimers (node:internal/timers:499:7)","stack":"Error: timeout of 5000ms exceeded\n    at e.exports (/mytestproject/node_modules/twilio-taskrouter/dist/index.commonjs2.js:10:83369)\n    at Timeout._onTimeout (/mytestproject/node_modules/twilio-taskrouter/dist/index.commonjs2.js:10:186399)\n    at listOnTimeout (node:internal/timers:556:17)\n    at processTimers (node:internal/timers:499:7)","exception":true,"date":"Wed Mar 24 2021 10:44:42 GMT-0400 (Eastern Daylight Time)"`

Is there anyway to handle this in nodejs gracefully?

**Comment by lqkallas** [comment]
Hi! Thank you for bringing this to our attention. We have improved the error handling in the 2.0.0 version.
