### ISSUE TITLE
(1.21.0) taskrouter.min.js:3 Heartbeat timed out. closing socket

### ISSUE THREAD

**Issue by rakeshkk16** [twilio/twilio-taskrouter.js#39]
If the user sets the computer on sleep for long interval then on reconnection it starts giving error
Websocket closed
Websocket has disconnected
Received a message of type [disconnected]
Websocket had an error.

Even though I tried creating new worker with existing token (i.e. new Twilio.TaskRouter.Worker(workerToken, true, null, null, true), or with new token, or with  worker.updateToken still the worker does not establishes connection again.
![Screenshot from 2021-03-25 14-21-33](https://user-images.githubusercontent.com/68590642/112445728-7810f780-8d75-11eb-9f91-e72693871ed6.png)

**Comment by GhazanfarKhan** [comment]
Any update we are facing similar issue, not receiving on method such as activity.update and so on.

**Comment by killian-dunne** [comment]
Am also experiencing this issue, would love to hear if anyone has found a cause! Thanks

**Comment by tuongleit** [comment]
![image](https://github.com/twilio/twilio-taskrouter.js/assets/41422637/9af4fc59-97e3-4bb2-81b9-49959b7a04d5)

Facing similar issues. Looking into to code, I see it is trying to re-create socket again when closing. 
Could have the function of destroying the web socket when needed?

**Comment by lqkallas** [comment]
Hello. Thank you for bringing this to our attention. Please try the latest version, WorkerClient has now disconnect and reconnect functionality to help solve this issue.
