### ISSUE TITLE
verifyJWT called but no longer exists

### ISSUE THREAD

**Issue by tcreeds** [twilio/twilio-taskrouter.js#4]
In TaskRouterBase, tools.verifyJWT is called, but verifyJWT was removed from Tools in 2.0.0. This throws an error when instantiating TaskRouterBase.
Using twilio-taskrouter 0.2.4 from npm.

<img width="436" alt="screen shot 2018-08-17 at 12 32 53 pm" src="https://user-images.githubusercontent.com/6759374/44277787-c652d700-a219-11e8-9e5c-654e8645abbb.png">

**Comment by charlesBochet** [comment]
This issue is still not fixed. Can we have an update?

**Comment by hli2021** [comment]
@wanjunsli Mind taking a look since SDK has been moved to TR team?

**Comment by AndreyTwilio** [comment]
Closing this issue, as it is no longer relevant
