### ISSUE TITLE
Make release-tool a dev dependency

### ISSUE THREAD

**Issue by ncausey** [twilio/twilio-taskrouter.js#5]
When using Flex and Taskrouter, we are running into an issue in our deployment pipeline where the release-tool dependency is being blocked from accessing that GitHub repo.

Could that dependency be made a dev dependency? I believe that would solve our issue of trying to download that behind our proxy.

**Comment by AndreyTwilio** [comment]
Hi @ncausey, I believe we are no longer using release-tool, so now it should be fine. Closing as it's state issue.
