### ISSUE TITLE
'on' does not exist on type Worker

### ISSUE THREAD

**Issue by josh08h** [twilio/twilio-taskrouter.js#50]
I am seeing a TS compilation error whereby 'on' is not defined on type 'Worker'. I think this is because the Worker class which is extending `NodeJS.EventEmitter` should be an interface as opposed to a class.

So instead of `export class Worker extends NodeJS.EventEmitter {` it should be `export interface Worker extends NodeJS.EventEmitter {`.

This may be since the release of Node > 14, see [here](https://github.com/electron/electron/issues/21612) for a similar issue.

**Comment by tim-lukacik** [comment]
While we wait for a proper fix, the tldr from the other thread is
`npm i @types/node@12`

**Comment by lqkallas** [comment]
Thank you for raising and I am sorry it has taken us so long to get back to you. We have updated dependencies for events, now 'on' should be available on Worker.
