### ISSUE TITLE
Shouldn't Task.setAttributes pass the task version in the request?

### ISSUE THREAD

**Issue by johnnywell** [twilio/twilio-taskrouter.js#53]
I'm experiencing conflicts in some tasks due to concurrent updates. So I'm tracking down all the places performing any updates to tasks: Backend systems, functions, and Flex plugins. I hope a can apply the [conflict resolution](https://www.twilio.com/docs/usage/mutation-and-conflict-resolution) suggested in the documentation. When investigating one of my plugins I realized this method doesn't handle the task version when setting the attributes. This could lead to the kind of conflict I'm trying to mitigate.

Is the version handling in the roadmap for this lib? In the meanwhile, there's a suggested way to handle the task update differently in Flex plugins?

https://github.com/twilio/twilio-taskrouter.js/blob/8587e0a92182da2615ce54de41b10184692463d5/lib/Task.js#L183-L194

**Comment by lqkallas** [comment]
Hello, Johnny! 

Thank you for bringing versioning to our attention. I am sorry it took us such a long time to get back to you. Versioning has now been added.
