### ISSUE TITLE
Add disconnectActivitySid as a parameter for Worker constructor

### ISSUE THREAD

**Issue by mperreux** [twilio/twilio-taskrouter.js#6]
In the original JS SDK there's a parameter in the Worker constructor for an activity to place the worker in upon disconnect. Is it possible to add that in this version? Thank you.
https://www.twilio.com/docs/taskrouter/js-sdk/worker#parameters

**Comment by lqkallas** [comment]
Hello, Michael! Thank you for bringing this to our attention. I am sorry it has taken so long for us to reply. At the moment we are not planning to add disconnectActivitySid as a parameter for Worker constructor to TR SDK v2. You can listen to the worker "disconnected" event and then update the worker to their disconnected activity.
