### ISSUE TITLE
Issue importing types

### ISSUE THREAD

**Issue by LiamMoorcroft** [twilio/twilio-taskrouter.js#7]
In my project I am using typescript and require Twilio types. Inside this repository I can see a types.d.ts file which is exporting all the different types. However when attempting to import these types they can not be found.

Looking in node modules at was is installed for the package and it appears the types file or an equivalent is not included. 

Could this be an issue with the package itself or the way in which I am trying to import the type?

**Comment by creedasaurus** [comment]
I think this would fix it. I was hoping for the same thing. #21

**Comment by banyard** [comment]
Waiting for this fix too.

**Comment by josh08h** [comment]
@jmarks-twilio Can we get this one merged please?

**Comment by creedasaurus** [comment]
PR has been updated.

**Comment by AndreyTwilio** [comment]
Hi guys, I believe this is done by now and can be closed. Please re-open if you have any other issues.
