### ISSUE TITLE
Not enough events emitted from web socket 

### ISSUE THREAD

**Issue by IAmConnorWilson** [twilio/twilio-taskrouter.js#8]
The taskQueue only has "ready" and "tokenExpired". 

We need to know when tasks have been added to a queue or any tasks in the queue have been updated.

**Comment by jack-tutor** [comment]
I know a very old (and closed) issue - but I am also running into this.  I want to subscribe to events about all tasks that exist.  I don't see in the documentation/type stub any calls to do this

**Comment by cancit** [comment]
Hello @jack-tutor, twilio-taskrouter.js sdk is a frontend sdk meant to be used by workers and via sdk you can only subscribe to tasks that are assigned to that worker. If you would like to process events for all the tasks, that can be handled in your backend via event callbacks. See https://www.twilio.com/docs/taskrouter/api/event/reference
