### ISSUE TITLE
TaskRouter Incompatibilities between Flex UI versions

### ISSUE THREAD

**Issue by dmitriy-kudelko** [twilio/twilio-taskrouter.js#90]
Hello,

I wasn't able to find reason for the following in TaskRouter release notes, but:
- `@twilio/flex-ui@1.33.3` comes with `twilio-taskrouter@^0.7.1`
- `@twilio/flex-ui@1.34.0` comes with `twilio-taskrouter@^0.5.9` (which is a lower version)

Prior to Flex UI 1.34.0 we relied on some `Worker` attributes and methods, part of which existed in TR `0.7.x` but didn't exist in TR `0.5.x`. As a result, when upgrading our custom plugin to `flex-ui@1.34.0` we're facing with compatibility issues. For example we used `Worker.fetchLatestVersion` method which we now cannot use with `flex-ui@1.34.0`.

First of all.. how/where can we track such unexpected breaking changes when a part of dependencies is downgraded whereas with the Flex UI package version is upgraded?

What would be an alternative to this `Worker.fetchLatestVersion` method in TR `0.5.x`? 

We're also aiming to have our code compatible with Flex UI 2.x as much as possible, and that is one of the issues which 'caused a negative effect on this goal.

**Comment by AndreyTwilio** [comment]
Hello @dmitriy-kudelko , thank you for raising this up. 
It was a temporary measure that we had to take. Currently, latest version of Flex UI 1.3x is [1.34](https://www.npmjs.com/package/@twilio/flex-ui/v/1.34.3?activeTab=code) that uses TR SDK ^0.8.1, which should not have this issue. 
Please update if you are still on version 1 or migrate to 2.x if possible. Also please feel free to re-open this issue if the problem still exists.
